version: '3.1'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver2019
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Password01
      SSQL_PID: Express
#    volumes:
#      - ./sqlserver-data:/var/opt/mssql
  php:
    build: ./php
    container_name: php8-sql
    ports:
      - 80:80
    volumes:
      - ./php/src:/var/www/html
