version: '3.1'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-2022
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Password01
      SSQL_PID: Express
    volumes:
      - ./sqlserver-data:/var/opt/mssql
  php:
    build: ./php
    container_name: php8-sql
    ports:
      - 8080:80
    volumes:
      - ./php/src:/var/www/html
  php-alpine:
    build: ./php-alpine
    container_name: php8-alpn
    ports:
      - 9000:9000
      - 8081:80
    volumes:
      - ./php/src:/var/www/html
