FROM php:8.1-apache

# Instalar extensiones necesarias
RUN apt-get update && apt-get install -y \
    unixodbc-dev \
    libgssapi-krb5-2 \
    && docker-php-ext-install pdo pdo_mysql

# Instalar driver SQL Server para PHP
RUN pecl install sqlsrv pdo_sqlsrv \
    && docker-php-ext-enable sqlsrv pdo_sqlsrv

# Copiar archivo php.ini
COPY ./php/php.ini /usr/local/etc/php/

# Configurar Apache
RUN a2enmod rewrite

# Copiar archivos de la aplicación
COPY ./src /var/www/html/

# Configurar permisos
#RUN chown -R www-data:www-data /var/www/html/ \
#    && chmod -R 755 /var/www/html/

