FROM php:8.2.20-apache

# Instalar las dependencias necesarias
RUN apt-get update && apt-get install -y \
    gnupg \
    apt-transport-https \
    unixodbc-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Agregar la clave y el repositorio de Microsoft
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/$(lsb_release -rs)/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update

# Instalar los controladores ODBC de SQL Server
RUN ACCEPT_EULA=Y apt-get install -y msodbcsql17

# Instalar las extensiones de PHP necesarias para SQL Server
RUN docker-php-ext-install pdo && docker-php-ext-enable pdo
RUN pecl install sqlsrv pdo_sqlsrv \
    && docker-php-ext-enable sqlsrv pdo_sqlsrv

# Reiniciar Apache para aplicar los cambios
RUN service apache2 restart

# Copiar los archivos de la aplicación al directorio web del contenedor
COPY ./src/ /var/www/html

# Establecer el directorio de trabajo
WORKDIR /var/www/html

# Configurar los puertos y los volúmenes según sea necesario
EXPOSE 80
VOLUME ["/var/www/html"]